blog/urls.py
from django.urls import path
from . import views
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', BlogView.as_view(), name='index'),
    path('like/', views.like, name='like'),
    path('me/', self_profile_view, name="self_profile"),
    path('profile/edit/', edit_profile_view.as_view(), name='edit_profile'),
    path('feedback/', views.add_feedback, name='add_feedback'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from users.forms import UserPasswordResetForm, UserPasswordResetNewForm

from users.views import (
    registration_view,
    logout_view,
    login_view,
    activate,
    password_reset_view,
    test,
)

from blog.views import (
    BlogView,
    profile_view,
    self_profile_view,
    frontend_view,
)

urlpatterns = [

    # frontend development
    path('1', test, name="frontend"),

    # admin backend
    path('admin/', admin.site.urls),

    # index blog
    path('', include('blog.urls', namespace='blog')),

    # blog detail page
    # path('<user_netid>/<post_id>')

    # register, login, logout
    path('register/', registration_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),

    # password reset
    path('accounts/password/reset/', password_reset_view, name='password_reset'),

    path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset/password_reset_done.html'),
     name='password_reset_done'),
 
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name = 'users/password_reset/password_reset_new.html',
        form_class= UserPasswordResetNewForm), name='password_reset_confirm'),
        
    path('accounts/password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
    
    # path for email verification
    path('activate/<uidb64>/<token>', activate, name='activate'),  
    
    path('<str:pk>/', profile_view.as_view(), name='profile'),
]


if settings.DEBUG:
    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
import uuid

def upload_location(instance, filename, **kwargs):
    file_path = 'blog/{author_netid}/{post_id}/{filename}'.format(
        author_netid = str(instance.blogpost.author.netid),
        post_id = str(instance.blogpost.id),
        filename=filename,
        )
    return file_path

class BlogPost(models.Model):
    title                   = models.CharField(max_length=50, null=True, blank=True)
    body                    = models.TextField(max_length=5000, null=False, blank=False)
    data_published          = models.DateTimeField(auto_now_add=True, verbose_name="data published")
    data_updated            = models.DateTimeField(auto_now_add=True, verbose_name="data updated")
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    id                      = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    slug                    = models.SlugField(max_length=100, blank=True, unique=True)
    likes                   = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like', default=None, blank=True)
    like_count              = models.BigIntegerField(default='0')

    def __str__(self):
        return str(self.author.netid) + " / " + self.title + " / " + str(self.data_published)

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.netid + "-" + instance.title + "-" + str(instance.id))

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

class Image(models.Model):
    blogpost                = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    image                   = models.ImageField(upload_to=upload_location, null=True, blank=True)

    def __str__(self):
        return str(self.blogpost.author.netid) + " / " + self.blogpost.title + " / " + str(self.blogpost.data_published)

class Feedback(models.Model):
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    feedback                = models.TextField(max_length=5000, null=False, blank=False)
    share                   = models.BooleanField(null=False, blank=False)
    date                    = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.author.full_name

blog/forms.py
from django import forms
from django.contrib import admin
from blog.models import BlogPost, Image, Feedback


class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body']

class UploadImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ['image',]

class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ['feedback', 'share',]

blog/views.py
from email import message
from email.mime import image
from multiprocessing import context
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.decorators import login_required

from users.models import Account, Profile
from blog.models import BlogPost, Image

from django.http import HttpResponse, JsonResponse

from blog.forms import CreateBlogPostForm, FeedbackForm

@login_required(login_url='/login/')
def create_new_post(request):
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)

        # link to user
        author = Account.objects.filter(email=request.user.email).first()
        post.author = author
        
        # create post models
        post.save()

        # create image models
        images = request.FILES.getlist('images')
        for image in images:
            Image.objects.create(blogpost=post, image=image)


@login_required(login_url='/login/')
def add_feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)

            # link to user
            author = Account.objects.filter(email=request.user.email).first()
            feedback.author = author
        
            # create post models
            feedback.save()

        next = request.POST.get('next', '/')
        return redirect(next)



# Index view for blog
class BlogView(View):
    def post(self, request):
        create_new_post(request)
        return redirect(request.path_info)

    def get(self, request):
        context = {}
        all_posts = BlogPost.objects.all().order_by('-data_published')
        context['posts'] = all_posts
        return render(request, 'blog/index.html', context)

class edit_profile_view(View):
    def post(self, request):
        return redirect(request.path_info)

    def get(self, request):
        context = {}
        return render(request, 'blog/edit-profile.html', context)

# Profile pages for each users
# @login_required(login_url='/login/')
class profile_view(View):
    def post(self, request, pk):
        create_new_post(request)
        return redirect(request.path_info)

    def get(self, request, pk):
        context = {}
        user_found = Account.objects.filter(netid=pk).first()
        if (user_found == None):
            return HttpResponse("No matching account", content_type='text/plain')
        else:
            user_posts = BlogPost.objects.filter(author=user_found).order_by('-data_published')
            context['user'] = user_found
            context['user_posts'] = user_posts
            if(user_found == request.user):
                return render(request, 'blog/user-profile.html', context)
            else:
                return HttpResponse("To see other people profile is still working on process", content_type='text/plain')


@login_required(login_url='/login/')
def self_profile_view(request):
    context = {}
    user_netid = request.user.netid
    return redirect("/%s/" % user_netid)

def post_view(request, user_netid, post_id):
    post = BlogPost.objects.filter(id=post_id).first()
    if (post == None):
        return HttpResponse("No matching post", content_type='text/plain')
    else:
        return render(request, 'blog/user-profile.html', {})


@login_required(login_url='/login/')
def like(request):
    if request.POST.get('action') == 'post':
        result = ''
        id = request.POST.get('postid')
        post = get_object_or_404(BlogPost, id=id)
        user = Account.objects.filter(email=request.user.email).first()
        if post.likes.filter(email=request.user.email).exists():
            post.likes.remove(request.user)
            post.like_count -= 1
            result = post.like_count
            post.save()
        else:
            post.likes.add(request.user)
            post.like_count += 1
            result = post.like_count
            post.save()
        return JsonResponse({'result': result,})

def frontend_view(request):
    return render(request, 'blog/popups/create-post-forum.html')

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <script src="https://kit.fontawesome.com/9fc067fd17.js" crossorigin="anonymous"></script>

    <!--script for purpose of ajax (no refresh page)-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/create-post-forum.css' %}" />
    <link rel="stylesheet" href="{% static 'css/feedback-forum.css' %}" />
    <link rel="stylesheet" href="{% static 'css/user-home.css' %}" />
    <link rel="stylesheet" href="{% static 'css/navigation-bar.css' %}">
    <link rel="stylesheet" href="{% static 'css/user-profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/edit.css' %}" >

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" integrity="sha256-5uKiXEwbaQh9cgd2/5Vp6WmMnsUr3VZZw0a8rKnOKNU=" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js" integrity="sha256-FZsW7H2V5X9TGinSjjwYJ419Xka27I8XPDmWryGlWtw=" crossorigin="anonymous"></script>
    <title>{% block title %} Queendom {% endblock title %}</title>
  </head>
  <body>
  {% include 'blog/navbar.html' %}

  {% include 'blog/floats/feedback-btn.html' %}

  {% include 'blog/popups/create-post-forum.html' %}
  {% include 'blog/popups/feedback-forum.html' %}

  {% block content %}


  {% endblock content %}
  
    <script src="{% static 'js/popup.js' %}"></script>
    <script src="{% static 'js/feedback.js' %}"></script>

  </body>

  </html>

blog/templates/blog/edit-profile.html
{% extends 'blog/base.html' %}

{% block title %} Queendom | Edit Profile {% endblock title %}

{% load static %}
{% block content %}

<!-- Edit Profile Page Start-->
<div class="container">
    <div class="edit-profile-container">
        <!--Leftbox Start-->
        <div class="leftbox">
            <nav-profile>
                <a onclick="tabs(0)" class="tab active prevent-select">                    
                    <i class="fa fa-user"></i>
                    Edit Profile
                </a>
                
                <a onclick="tabs(1)" class="tab prevent-select">
                    <i class="fas fa-key"></i>
                    Change Password
                </a>

                <a onclick="tabs(2)" class="tab prevent-select">
                    <i class="fas fa-lock"></i>
                    Privacy
                </a>

                <a onclick="tabs(3)" class="tab prevent-select">
                    <i class="fa fa-question-circle"></i>
                    Help
                </a>
            </nav-profile>
        </div>
        <!--Leftbox End-->

        <!--Rightbox Start-->
        <div class="rightbox">
            <!--Personal Info-->
            <div class="profile tabShow">
                <div class="user-profile"> <!--Photo-->
                    <aside class="col-name">
                        <img src="{{ request.user.profile.profileimg.url }}">
                    </aside>
                    <div class="photochange">
                        <h2>{{ request.user.full_name }}</h2>
                        <a href="#">Change Profile Photo</a>
                    </div>
                </div>

                <div class="profile-col">
                    <aside class="col-name">
                        <label for="user-fullname">
                            Full Name
                        </label>
                    </aside>
                    <input type="text" class="input-text" value="{{ request.user.full_name }}">
                </div>

                <div class="profile-col">
                    <aside class="col-name">
                        <label for="user-email">
                            Email
                        </label>
                    </aside>
                    <input type="text" class="input-text" disabled="disabled" value="{{ request.user.email }}">
                </div>

                <div class="profile-col">
                    <aside class="col-name">
                        <label for="user-bio">
                            Bio
                        </label>
                    </aside>
                    <textarea type="text" class="input-text">你好</textarea>
                </div>

                <div class="profile-col">
                    <aside class="col-name">
                        <label for="user-gender">
                            Gender
                        </label>
                    </aside>
                    
                    <select class="input-text" name="gender" id="gender">
                        <option value="female">Female</option>
                        <option value="male">Male</option>
                        <option value="prefer not to say">Prefer Not To Say</option>
                    </select>
                </div>

                <div class="profile-col">
                    <aside class="col-name">
                        <label for="user-status">
                            Status
                        </label>
                    </aside>

                    <select class="input-text" name="status" id="identity-status">
                        <option value="current-student">Current Student</option>
                        <option value="future-student">Future Student</option>
                        <option value="faculty-staff">Faculty & Staff</option>
                        <option value="alumni">Alumni</option>
                    </select>
                </div>

                <div class="profile-col">
                    <aside class="col-name">
                        <label for="user-status-yos">
                            Year of Study
                        </label>
                    </aside>
                    <select class="input-text" name="status-yos" id="status-yos">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                    </select>
                </div>

                <div class="profile-col">
                    <aside class="col-name">
                        <label></label>
                    </aside>
                    <button class="save-btn">Save</button>
                </div>
            </div>

            <!--Change Password-->
            <div class="password tabShow">
                <h1>Change Password</h1> 
                <h2>Old Password</h2>
                <input type="text" class="input">
                <h2>New Password</h2>
                <input type="text" class="input">
                <h2>Confirm New Password</h2>
                <input type="text" class="input">
                <button class="save-btn">Save</button>
                <button class="forget-passwordbtn" id="forgot-password-btn">
                    Forgot Password?
                    </button>
            </div>

            <!--Privacy-->
            <div class="privacy tabShow">
                <h1>Privacy</h1> 
                <h2>Blocked List 
                    <i class="fas fa-angle-down" onclick="blockedMenuToggle()"> </i>
                </h2> <!--Full Name-->

                <!--Blocked List Menu Start-->
                <div class="blocked-menu">
                    <div class="blocked-menu-inner">
                        <div>
                            <h2>Jonas</h2>
                        </div>
                        <select name="onoff" id="onoff">
                            <option value="on">On</option>
                            <option value="off">Off</option>
                        </select>
                    </div>
                    <hr> <!--setting menu分割线-->
                    <div class="blocked-menu-inner">
                        <div>
                            <h2>Jonas</h2>
                        </div>
                        <select name="onoff" id="onoff">
                            <option value="on">On</option>
                            <option value="off">Off</option>
                        </select>
                    </div>
                    <hr> <!--setting menu分割线-->
                    <div class="blocked-menu-inner">
                        <div>
                            <h2>Jonas</h2>
                        </div>
                        <select name="onoff" id="onoff">
                            <option value="on">On</option>
                            <option value="off">Off</option>
                        </select>
                    </div>
                    <hr> <!--setting menu分割线-->
                    <div class="blocked-menu-inner">
                        <div>
                            <h2>Jonas</h2>
                        </div>
                        <select name="onoff" id="onoff">
                            <option value="on">On</option>
                            <option value="off">Off</option>
                        </select>
                    </div>
                </div>
                <!--Blocked List Menu End-->
                
                <button class="save-btn">Save</button>
            </div>

                <!--Help-->
                <div class="help tabShow">
                <h1>Help</h1> 
                <div class="write-post-container"> <!--Write-->
                    

                    <div class="post-input-container"> <!--Input-->
                        <h3>Tell Us Your Needs</h3>
                        <div class="title-box">
                            <input type="text" placeholder="TITLE HERE... 0-20 words"> <!--title-->
                        </div>
                        <textarea rows="3" placeholder="Post your comments here to help us to improve our development..."></textarea>
                        <button class="save-btn">SENT</button>
                        
                    </div>
                </div>
            </div>

        
        </div>
        <!--Rightbox End-->
    </div>
</div>
<!--Edit Profile Page End-->
<script src="{% static 'js/edit-profile.js' %}"></script>
{% endblock content %}

blog/templates/blog/navbar.html
{% load static %}
<!--Navigation Bar Start-->
<nav>
    <!--left side navigation bar start-->
    <div class="nav-left">
        <div class="nav-left-inner">
            <a href="{% url 'blog:index'%}">
                <div class="logo"><img src="{% static 'img/logo.png' %}"></div>
            </a>
        </div>
    </div>
    <!--left side navigation bar end-->


    <!--Middle side navigation bar start-->
    <div class="nav-middle">
        <div class="search-box">
            <div class="search-box-inner">
                <img src="{% static 'img/search.png' %}" alt="">
                <input type="text" placeholder="Search">
            </div>
        </div>
    </div>
    <!--Middle side navigation bar end-->


    <!--right side navigation bar start-->
    <div class="nav-right">
        
        <ul> 
            {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'blog:index'%}" class="nav-icon"> <!--Home Icon-->
                    <i class="fas fa-home"></i>
                </a>
            
            </li>
            <li>
                <a role="button" class="create-post-icon"> <!--Post Icon-->
                    <i class="fas fa-plus-circle"></i>
                </a>
            </li>
            <li>
                <a class="nav-icon active" id="messages-notification" onclick="navigationsMenuToggle()"> <!--Notification Icon-->
                    <i class="fas fa-bell"><small class="notification-count">6</small></i>
                </a>
            </li>
            {% endif %}
            
        </ul>
        {% if request.user.is_authenticated %}
        <div class="nav-user-icon" onclick="settingsMenuToggle()">
            <img id="nav_user_icon" src="{{ request.user.profile.profileimg.url }}" alt="">
        </div>
        {% else %}
        <div class="login-register-btn">
            <a href="{% url 'login'%}">
                Log in/Register
            </a>
        </div>
        {% endif %}
    </div>
    <!--right side navigation bar end-->



    <!----------------User setting menu Start----------------->
    <div class="settings-menu arrow-top" id="settings_menu">

        <div class="settings-menu-inner" id="settings_menu">
            {% if request.user.is_authenticated %}
            
            <a href="{% url 'blog:self_profile' %}" class="user-profile">
                <img src="{{ request.user.profile.profileimg.url }}" id="settings_menu">
                <div id="settings_menu">
                    <h2 id="settings_menu">{{ request.user.full_name }}</h2>
                </div>
            </a>
            

            <hr> <!--setting menu分割线-->

            <a href="{% url 'logout' %}" class="setting-links">
                <img src="{% static 'img/logout.png' %}" class="settings-icon">
                <div class="setting-links-content">
                    Logout
                    <img src="{% static 'img/arrow.png' %}" width="10px">
                </div>
            </a>

            {% else %}
            <div class="user-profile"> <!--Line 1-->
                <img src="{% static 'img/log-icon.png' %}">
                <div>
                    <p>Sign In/Sign Up</p>
                    <a href="/login">Log in/Sign up with your account</a>
                </div>
            </div>
            <hr> <!--setting menu分割线-->
            {% endif %}
        </div>
    </div>
    <!----------------User settisng menu End----------------->

</nav>

<script src="{% static 'js/nav-bar.js' %}"></script>
<!--Navigation Bar End-->

blog/templates/blog/user-profile.html
{% extends 'blog/base.html' %}

{% block title %} Queendom | @{{ user.full_name }} profile {% endblock title %}

{% load static %}
{% load id_change %}
{% block content %}

<!--------Profile Page Start-------->

<div class="container">
    <!--Left side bar-->
    <div class="left-sidebar"></div>

    <!--Main Content-->
    <div class="main-content">
        <div class="user">
            <div class="user-profile"> <!--Photo-->
                <img src="{{ user.profile.profileimg.url }}">
                <div class="photochange">
                    <h2>{{ user.full_name }}</h2>
                    <p>Peace & Love</p>
                    <p>Health Studies</p>
                </div>
                <!--<a href="#"><i class="fas fa-user-friends" onclick="friendMenuToggle()"></i></a>-->
                <a href="/profile/edit/"><i class="fa-solid fa-pen"></i>Edit Profile</a>
            </div>

            <div class="follow-info">
                <a href="" class="follower">
                    <span>
                        10
                    </span>
                     Followers
                </a>
                <a href="" class="following">
                    <span>
                        20
                    </span>
                     Followings
                </a>
            </div>
        </div>
        
        <!----Buttons Start---->
        <div class="profile-list">

            <button class="btn-view-post profile-tabs active" onclick="profile_tabs(0)">
                <span>{{ user_posts.count }}</span>&nbspPOST
            </button>

            <button class="btn-view-post profile-tabs" onclick="profile_tabs(1)">
                SAVED
            </button>

        </div>
        <hr> <!--setting menu分割线-->
        <!----Buttons End---->

        <!-------- User Posts Content-------->
        <div class="user-post-content profile-tabshow">

            {% for post in user_posts %}
            <div class="self-post-container" id="{{ post.id }}">
                <div class="post-row">
                    <div class="user-profile">
                        <a href="/">
                            <img src="{{ post.author.profile.profileimg.url }}">
                        </a>
                        <div class="post-user-profile">
                            <p>{{ post.author.full_name }}</p>
                            <span>{{ post.data_published }}</span>
                        </div>
                    </div>
                    <a href="#"><i class="fas fa-ellipsis-v" onclick="selfmoreMenuToggle()"></i></a>
                </div>
    
                
                <h2 class="post-title">
                    <a href="{{ post.author.netid }}/{{ post.id }}">
                        {{ post.title }}
                    </a>
                </h2>
                
    
                <p class="post-text">
                    {{ post.body }}
                </p>
                
                {% if post.image_set.count != 0 %}
                <section id="{{ post.id.hex|to_splider_id }}" class="splide" aria-label="Beautiful Images">
                    <div class="splide__track">
                            <ul class="splide__list">
                                {% for image in post.image_set.all %}
                                <li class="splide__slide">
                                    <img src="{{ image.image.url }}" alt="">
                                </li>
                                {% endfor %}
                            </ul>
                    </div>
                </section>
                
                <script>
                    new Splide( '#{{ post.id.hex|to_splider_id }}', {
    
                    } ).mount();
                </script>
                {% endif %}
    
                <div class="post-bottom">
                    <div class="activity-icons">
                        <div class="icons">
                            
                            {% if request.user.is_authenticated %}
                            <button id="like-button" value="{{post.id}}">
                                    <i class="fas fa-heart like-i 
                                    {% if post.likes|users_liked:request.user.email %}
                                    active
                                    {% endif %}">
                                        
                                        <span class="like_count" id="like_count">
                                        {% if post.like_count != 0 %}
                                            {{post.like_count}}
                                        {% endif %}
                                        </span>
                                        
                                    </i>
                            </button>
                            {% else %}
                            <button id="like-button-inactive" value="{{post.id}}">
                                <a style="text-decoration: none" href="{% url 'login' %}">
                                    <i class="fas fa-heart like-i">
                                    
                                    <span class="like_count" id="like_count">
                                    </span>
                                    
                                    </i>
                                </a>
                            </button>
                            {% endif %}
                        </div>
                        <div class="icons">
                            <button id="fav-button" value="{{post.id}}">
                                    <i class="fas fa-star"></i>
                            </button>
                        </div>
                        <div class="icons">
                            <button id="share-button" value="{{post.id}}">
                                    <i class="fas fa-share"></i>
                            </button>
                        </div>
                    </div>
                    <div class="comment-box">
                        <input type="text" placeholder="Comment...">
    
                        <div class="send-comment">
                            <button id="comment-button" value="{{post.id}}">
                                <i class="far fa-paper-plane"></i> <!--Comment-Send Icon-->
                            </button>
                        </div>
                    </div>
                    
                </div>
                
            </div>
            {% endfor %}
        </div>
        <!-------- User Post Content End-------->

        <!-------- User Saved Posts Content -------->
        <div class="user-saved-content profile-tabshow">
            You haven't save any posts yet.
        </div>
        <!-------- User Saved Posts Content End -------->

    </div>    

    <!--Right side bar-->
    <div class="right-sidebar"></div>
</div>
<script src="{% static 'js/user-profile.js' %}"></script>
<!--------Profile Page Ending-------->
{% endblock content %}