blog/urls.py
from django.urls import path
from . import views
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', BlogView.as_view(), name='index'),
    path('like/', views.like, name='like'),
    path('me/', self_profile_view, name="self_profile"),
    path('profile/edit/', edit_profile_view.as_view(), name='edit_profile'),
    path('feedback/', views.add_feedback, name='add_feedback'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from users.forms import UserPasswordResetForm, UserPasswordResetNewForm

from users.views import (
    registration_view,
    logout_view,
    login_view,
    activate,
    password_reset_view,
    test,
)

from blog.views import (
    BlogView,
    profile_view,
    self_profile_view,
    frontend_view,
)

urlpatterns = [

    # frontend development
    path('1', test, name="frontend"),

    # admin backend
    path('admin/', admin.site.urls),

    # index blog
    path('', include('blog.urls', namespace='blog')),

    # blog detail page
    # path('<user_netid>/<post_id>')

    # register, login, logout
    path('register/', registration_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),

    # password reset
    path('accounts/password/reset/', password_reset_view, name='password_reset'),

    path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset/password_reset_done.html'),
     name='password_reset_done'),
 
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name = 'users/password_reset/password_reset_new.html',
        form_class= UserPasswordResetNewForm), name='password_reset_confirm'),
        
    path('accounts/password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
    
    # path for email verification
    path('activate/<uidb64>/<token>', activate, name='activate'),  
    
    path('<str:pk>/', profile_view.as_view(), name='profile'),
]


if settings.DEBUG:
    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
import uuid

def upload_location(instance, filename, **kwargs):
    file_path = 'blog/{author_netid}/{post_id}/{filename}'.format(
        author_netid = str(instance.blogpost.author.netid),
        post_id = str(instance.blogpost.id),
        filename=filename,
        )
    return file_path

class BlogPost(models.Model):
    title                   = models.CharField(max_length=50, null=True, blank=True)
    body                    = models.TextField(max_length=5000, null=False, blank=False)
    data_published          = models.DateTimeField(auto_now_add=True, verbose_name="data published")
    data_updated            = models.DateTimeField(auto_now_add=True, verbose_name="data updated")
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    id                      = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    slug                    = models.SlugField(max_length=100, blank=True, unique=True)
    likes                   = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like', default=None, blank=True)
    like_count              = models.BigIntegerField(default='0')

    def __str__(self):
        return str(self.author.netid) + " / " + self.title + " / " + str(self.data_published)

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.netid + "-" + instance.title + "-" + str(instance.id))

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

class Image(models.Model):
    blogpost                = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    image                   = models.ImageField(upload_to=upload_location, null=True, blank=True)

    def __str__(self):
        return str(self.blogpost.author.netid) + " / " + self.blogpost.title + " / " + str(self.blogpost.data_published)

class Feedback(models.Model):
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    feedback                = models.TextField(max_length=5000, null=False, blank=False)
    share                   = models.BooleanField(null=False, blank=False)
    date                    = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.author.full_name

blog/forms.py
from django import forms
from django.contrib import admin
from blog.models import BlogPost, Image, Feedback


class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body']

class UploadImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ['image',]

class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ['feedback', 'share',]

blog/views.py
from email import message
from email.mime import image
from multiprocessing import context
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.decorators import login_required

from users.models import Account, Profile
from blog.models import BlogPost, Image

from django.http import HttpResponse, JsonResponse

from blog.forms import CreateBlogPostForm, FeedbackForm

@login_required(login_url='/login/')
def create_new_post(request):
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)

        # link to user
        author = Account.objects.filter(email=request.user.email).first()
        post.author = author
        
        # create post models
        post.save()

        # create image models
        images = request.FILES.getlist('images')
        for image in images:
            Image.objects.create(blogpost=post, image=image)


@login_required(login_url='/login/')
def add_feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)

            # link to user
            author = Account.objects.filter(email=request.user.email).first()
            feedback.author = author
        
            # create post models
            feedback.save()

        next = request.POST.get('next', '/')
        return redirect(next)



# Index view for blog
class BlogView(View):
    def post(self, request):
        create_new_post(request)
        return redirect(request.path_info)

    def get(self, request):
        context = {}
        all_posts = BlogPost.objects.all().order_by('-data_published')
        context['posts'] = all_posts
        return render(request, 'blog/index.html', context)

class edit_profile_view(View):
    def post(self, request):
        return redirect(request.path_info)

    def get(self, request):
        context = {}
        return render(request, 'blog/edit-profile.html', context)

# Profile pages for each users
# @login_required(login_url='/login/')
class profile_view(View):
    def post(self, request, pk):
        create_new_post(request)
        return redirect(request.path_info)

    def get(self, request, pk):
        context = {}
        user_found = Account.objects.filter(netid=pk).first()
        if (user_found == None):
            return HttpResponse("No matching account", content_type='text/plain')
        else:
            user_posts = BlogPost.objects.filter(author=user_found).order_by('-data_published')
            context['user'] = user_found
            context['user_posts'] = user_posts
            if(user_found == request.user):
                return render(request, 'blog/user-profile.html', context)
            else:
                return HttpResponse("To see other people profile is still working on process", content_type='text/plain')


@login_required(login_url='/login/')
def self_profile_view(request):
    context = {}
    user_netid = request.user.netid
    return redirect("/%s/" % user_netid)

def post_view(request, user_netid, post_id):
    post = BlogPost.objects.filter(id=post_id).first()
    if (post == None):
        return HttpResponse("No matching post", content_type='text/plain')
    else:
        return render(request, 'blog/user-profile.html', {})


@login_required(login_url='/login/')
def like(request):
    if request.POST.get('action') == 'post':
        result = ''
        id = request.POST.get('postid')
        post = get_object_or_404(BlogPost, id=id)
        user = Account.objects.filter(email=request.user.email).first()
        if post.likes.filter(email=request.user.email).exists():
            post.likes.remove(request.user)
            post.like_count -= 1
            result = post.like_count
            post.save()
        else:
            post.likes.add(request.user)
            post.like_count += 1
            result = post.like_count
            post.save()
        return JsonResponse({'result': result,})

def frontend_view(request):
    return render(request, 'blog/popups/create-post-forum.html')

blog/templates/blog/popups/create-post-forum.html
{% load static %}

<!----------------Create Post menu Start----------------->
<div class="menu-background" id="create-post-forum">
    <div class="createpost-menu">
        <div class="header">
            <h2>Create Post</h2>
            <label for="click" class="fas fa-times" onclick="closeCreatePostMenu()"></label>
        </div>
        <div class="createpost-menu-inner">
            
            <div class="create-post-container"> <!--Write-->
                <div class="user-profile">
                    <a href="http://127.0.0.1:5500/Queendom/user-profile.html">
                        <img src="{{ request.user.profile.profileimg.url }}">
                    </a>
                    <div>
                        <p>{{ request.user.full_name }}</p>
                        <select name="privacy" id="privacy">
                            <option value="Public">Public</option>
                            <option value="Privacy">Private</option>
                        </select>
                    </div>
                </div>
                <form method="POST" id="post_form" enctype="multipart/form-data">{% csrf_token %}
                    
                    <div class="post-input-container"> <!--Input-->
                        <div class="title-box">
                            <input type="text" placeholder="Title..." name="title"> <!--title-->
                        </div>
                        <textarea name="body" id="message" rows="8" placeholder="Post your ideas here..." required></textarea><!--body-->
                        <div id="display_image"></div>
                        <div class="file-upload">
                            <!--
                            <img src="{% static 'img/1.jpeg' %}" class="post-img" id="forum-post-img">
                            <button id="delete-img-btn" class="img-btn fa-solid fa-trash" type="button" onclick="delete_input_files()"></button>
                            <button id="prev-img-btn" class="img-btn-bg img-btn fa-solid fa-angle-left" type="button" onclick=""></button>
                            <button id="next-img-btn" class="img-btn-bg img-btn fa-solid fa-angle-right" type="button" onclick=""></button>
                            <button id="add-img-btn" class="img-btn-bg img-btn fa-solid fa-plus" type="button" onclick=""></button>-->
                            <div class="icon" id="file-upload-item">
                                <i class="fas fa-images"></i>
                            </div>
                            <div class="up-header" id="file-upload-item">
                                Drag photos here
                            </div>
                            <label type="button" for="image_input" class="file-upload-button" id="file-upload-item">
                                Upload from computer
                            </label>
                            
                        </div>
                        <div class="post-forum-bottom">
                            <!--Icons of Post-->
                            <input name="images" type="file" id="image_input" multiple accept="image/*" hidden/>
                            <input name="add_more_imgs" type="file" id="add_more_imgs" multiple accept="image/*" hidden/>
                            <!--<a href="#"><i class="fas fa-grin-alt" onclick="feelingsMenuToggle()"> Feelings</i></a>-->
                            <button class="btn" type="submit" id="post-btn">Post</button>
                        </div>
                    </div>
                </form>
            </div>                     
        </div>
    </div>
</div>
<!----------------Create Post menu End----------------->

blog/templates/blog/popups/feedback-forum.html
{% load static %}

<div class="menu-background" id="feedback-forum">
    <div class="feedback-forum">
        <div class="close-feedback-btn">
            <label for="click" class="fas fa-times" onclick="closeFeedbackForum()"></label>
        </div>
        <div class="feedback-head">
            <img src="{% static 'img/logo.png' %}" alt="logo">
            <div class="feedback-title">
                <h3>
                    Feedback
                </h3>
            </div>
        </div>

        <form action="{% url 'blog:add_feedback' %}" method="POST">
            {% csrf_token %}
            <div class="feedback-container">
                <div class="feedback-detail">
                    <label>
                        Tell us how can we improve:
                    </label>
                    <textarea name="feedback" id="message" rows="8" placeholder="Type here..." required></textarea>
                </div>
                
                <div>
                    <label>
                        Will you share this site to your friends?
                    </label>
                    <input type="checkbox" name="share">
                </div>

                
                <button class="btn" type="submit" id="post-btn">Send</button>

            </div>
        </form>
    </div>
    
</div>